### PR TITLE
style(readme): fix typo

### PR DESCRIPTION
**Pull request by lastnod**
(Docs): Readme

orthographe ==> contin(u)o(u)s

ras

### CODE REVIEW

**Comment by ghpabs** [comment]
Thanks. I'll merge it if you just update the commit message to follow the contribution guideline.

https://github.com/ghpabs/angular2-seed-project/blob/master/.github/CONTRIBUTING.md#commit-message-format

**Comment by pas2al** [comment]
I thought it would change the commit message. Reverted.

**Comment by ghpabs** [comment]
Lovely thanks @pas2al

**Comment by ghpabs** [comment]
The Git history got a bit mangled but oh well... :-)

**Comment by pas2al** [comment]
Ya, i don't like that too. Next time i know better ;-)

**Pull request merged**
